services:
  navidrome:
    image: deluan/navidrome:latest
   # user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_LOGLEVEL: debug
    volumes:
      - "./data:/data"
      - "/home/user/Downloads/SoundCloud:/music:ro"
