apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: temp-checker
type: Opaque
stringData:
  API_TOKEN: "1337015126:AsdfeweawvmuzIMgWthatoneisrealZsIUvmaA"
  CHAT_ID: "1212122846"
  WORKER_IP: "192.168.88.79"
  MASTER_IP: "192.168.88.80"
  PORT: "8080"
