apiVersion: v1
kind: Secret
metadata:
  name: temp-checker-secrets
  namespace: temp-checker
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "12312312:SDFHKJSDFJKS"
  TELEGRAM_CHAT_ID: "1254125125"
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-secret
  namespace: temp-checker
type: Opaque
stringData:
  id_ed25519: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbAABAAAAMwAAAAtzc2gtZW
    dUm3eXR1v+Ebb9GnFMuMJRQJk9S0mrbJbQkA8nTohu8vsx
    5rrsSinjGgx75T4tz+e4AAAACXVzZXJAYXJjaAECAwQ=
    -----END OPENSSH PRIVATE KEY-----
  ssh_config: | 
    Host 192.168.88.80 
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null